### PR TITLE
Added Russian translation, a very necessary Builder!

### PR DESCRIPTION
**Pull request by rupelodn**
Hello, Slorelee, thank you for the necessary Builder!
I am a blind user, it is difficult for me to use many applications, but your development suits me.
I understand the purpose of all links and buttons in programs, but it's nicer and faster to work in my native language.
That's why I decided to translate your application into Russian.
I hope this will contribute to increasing the popularity of your Builder.
I couldn't write to you on theoven.
My account got lost after reopening the forum in the summer.
I wish you good luck, goodbye!

### CODE REVIEW

**Comment by slorelee** [comment]
Hi, rupelodn

Thanks for the Russian translation.

WimBuilder2\assets\i18n\*.js is UTF-8 encoding, your ru-RU.js is UTF-16LE,
But the characters show correctly, I merged your pull request.

**Comment by rupelodn** [comment]
Hi slorelee, the rest of the files I saved were also in UTF-16 LE encoding.
Should they be in UTF-8? bom or no bom?
This is my flaw - I was looking at other languages, and I thought that UTF-16 LE is correct.
I also looked that in \Windows\Inf files are encoded in UTF-16 LE.
Also in \Windows\System32\DriverStore\ru-RU files *.inf_loc are also in this encoding.
Therefore, I decided to leave this encoding so that the messages in Russian that can be transmitted to the PE registry are not distorted.
Today I decided to apply the WimBuilder2\AppData\Projects\WIN10XPE\10-MyCustom\MyContextMenu patch and noticed that the menu name "Restart Explorer" is not written correctly in the finished build.
Can i really convert all files to UTF-8?
If so, I will do it as soon as possible.
good luck, regards, 
rupelodn (or Ruslan Kolodyazhni, Russia, Rostov-on-Don).

**Comment by slorelee** [comment]
> the rest of the files I saved were also in UTF-16 LE encoding.

The rest is fine. assets\i18n\\*.js is load by HTML <script src='...'>, I thought it only support UTF-8,
but seem the UTF-16 LE is also good.
So, leave it as UTF-16 LE is fine. No need to update it.

>the menu name "Restart Explorer" is not written correctly in the finished build.

```
if ($app_host_lang == $lang) {
    $patches_var['i18n.restart_explorer_item'] = "Перезапустить Проводник";
}
```

Your system to build the PE, and the lang of the PE is same, so it will use the native language, otherwise it will be in English.

Maybe another reason, you use the OLD MyContextMenu.

WimBuilder2\\**AppData** used to keep the your customed items.
The one on github is **AppData.tmpl**, It will be copied at the first run, but if user has the old version,
it will be skipped.

Delete the AppData will use the new updated AppData.tmpl. **But make sure, you got the backup of your AppData.**

**Comment by rupelodn** [comment]
> if ($app_host_lang == $lang) {
    $patches_var['i18n.restart_explorer_item'] = "Перезапустить Проводник";
}
> 
Yes.
> Maybe another reason, you use the OLD MyContextMenu.
WimBuilder2\AppData used to keep the your customed items. />
> 
No, I update last files from github master, and add manually WimBuilder2\vendor
from theoven's archive.
Now I'm experiencing everything, and I often reset the settings by deleting the AppData folder.

**Pull request merged**
