### PR TITLE
Create ko-KR.js

### PR DESCRIPTION
**Pull request by nonamemanSEO**
[ko-KR.js.txt](https://github.com/slorelee/wimbuilder2/files/2816295/ko-KR.js.txt)
add new file translated

@@ You must erase the file extension (.txt)

### CODE REVIEW

**Comment by nonamemanSEO** [comment]
[ko-KR.js.txt](https://github.com/slorelee/wimbuilder2/files/2816431/ko-KR.js.txt)
add new file translated
@@ You must erase the file extension (.txt)

I'm sorry I made a mistake because I'm not good at using Github.

**Comment by nonamemanSEO** [comment]
WOW~ 
Thank you very much for doing such a hard work for me.
I'm so sorry you've been busy.
Just get some rest.
It's time to {relex} of your attractive signature : slo{r}e :)

**Comment by slorelee** [comment]
@nonamemanSEO 

Here is the guidline, please check it.
https://github.com/slorelee/wimbuilder2/issues/9

**Comment by nonamemanSEO** [comment]
> @nonamemanSEO
> 
> Here is the guidline, please check it.
> #9

Thank you, slore ~

**Comment by nonamemanSEO** [comment]
Close because test was completed

**Pull request closed without merging**
